name: Playwright Tests
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        check: [eslint, prettier] # Define Parallel checks
      fail-fast: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm' # Cache 50% faster
      - name: Install dependencies
        run: npm ci --frozen-lockfile
      - name: ${{ matrix.check }}
        run: npm run check:${{ matrix.check }}
  ui-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: lint-checks # Expect lint-checks pass to start
    strategy:
      matrix:
        env: [stg] # [dev, stg] for multi-env parallel execution
        shard: [1/1]
      fail-fast: true # If one job fail, abbort parallel jobs
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      # - name: Run Playwright  # ← Docker mágico
      #   uses: microsoft/playwright-github-action@v2
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests (${{ matrix.env }})
        env:
          ENV: ${{ matrix.env }}
          BASE_URL_FRONT: ${{ secrets.BASE_URL_FRONT }}
          BASE_URL_API: ${{ secrets.BASE_URL_API }}
          HEADLESS: 'true'
          CI: 'true'
        # run: npm run test:${{ matrix.env }}:${{ (matrix.env == 'dev' && 'smoke') || 'full' }}
        run: npm run test:${{ matrix.env }}:${{ (matrix.env == 'dev' && 'smoke') || 'full' }} --shard ${{ matrix.shard }}
        # Create 'blob-report' folder where it will put all the reports

      - name: Upload Blob report to GitHub Actions Artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: merged-reports-as-blob # Naming the uploaded file
          path: blob-report # Path where reports are stored
          retention-days: 15 # Suggested 90

  merge-reports-and-upload:
    if: always()
    needs: [ui-tests]
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Set a timestamp
        id: timestamp
        run: echo "timestamp=$(date -utc +%Y%m%d_%H%M%SZ)" > "$GITHUB_OUTPUT"
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install Deps
        run: npm ci
      # Download report previously uploaded to merge then and create one single small html report
      - name: Download blob reports form Github Actions Artifacts
        uses: actions/download-artifact@v7
        with:
          name: merged-reports-as-blob # Name of the file stored as artifact (as uploaded at the previously job)
          path: downloaded-merged-reports-as-blob # Name of the folder where the download will be saved
      # User Playwright to generate a report and store it inside '/playwright-report' folder
      - name: Merge the blobs into one single HTML Report
        run: npx playwright merge-reports --reporter html ./downloaded-merged-reports-as-blob

      - name: /[OPTIONAL] Upload full html report to artifacts history
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ steps.timestamp.outputs.timestamp }} # Name of the saved on history
          path: playwright-report # Path where the reports are
          retention-days: 30 # Suggested 90. Set 30 as a first experiment
